/** FAQ « Avocat escroquerie et fraude » — source unique, partagée par
 *  l’affichage (section FAQ) ET le JSON-LD FAQPage, pour garantir un texte
 *  strictement identique entre les deux (exigence d’éligibilité). Texte repris
 *  VERBATIM des réponses affichées de la maquette — aucune reformulation.
 */
export type FaqItem = { q: string; a: string };

export const FAQ_ITEMS: FaqItem[] = [
  { q: "La banque doit-elle rembourser une opération que je n'ai pas autorisée ?", a: "Le remboursement intervient aussitôt que l'établissement est informé de l'opération, et au plus tard à la fin du premier jour ouvrable suivant, sauf s'il a de bonnes raisons de soupçonner une fraude de l'utilisateur et qu'il les communique par écrit à la Banque de France. La charge de la preuve lui incombe : l'utilisation de l'instrument de paiement enregistrée par le prestataire ne suffit pas nécessairement à prouver que l'opération était autorisée ni qu'une négligence grave a été commise. Ce régime peut être aménagé par contrat pour les clients qui ne sont pas des consommateurs." },
  { q: "Ma banque invoque ma négligence grave après un spoofing. Est-ce fondé ?", a: "Pas automatiquement. Par arrêt du 23 octobre 2024 (n° 23-16.267), la chambre commerciale a rappelé que la charge de la preuve de la négligence grave, au sens de l'article L. 133-19 du code monétaire et financier, pèse sur la banque lorsque le client est victime d'un spoofing téléphonique. L'affichage du numéro réel de l'établissement est précisément ce qui a désarmé la vigilance de la victime." },
  { q: "J'ai validé l'opération moi-même. Ai-je encore un recours ?", a: "Oui, et souvent le meilleur. Le consentement se donne à une opération de paiement déterminée, non à un geste d'authentification isolé de son objet. Lorsque la validation a été présentée comme le blocage d'une fraude ou une mise en sécurité du compte, il faut déterminer si le consentement a porté sur le paiement réellement exécuté : selon le contenu des écrans, des messages et des informations affichées au moment de la validation, l'opération peut être contestée comme non autorisée et le remboursement demandé sur le fondement de l'article L. 133-18 du code monétaire et financier, la responsabilité de l'établissement étant à défaut recherchée sur le devoir de vigilance. Il en va autrement lorsque le virement a été voulu vers un bénéficiaire cru légitime : le recours se fonde alors sur la vigilance et l'anomalie apparente." },
  { q: "Quel délai pour contester une opération frauduleuse ?", a: "Treize mois à compter de la date de débit, selon l'article L. 133-24 du code monétaire et financier. Ce délai vise la contestation des opérations non autorisées ou mal exécutées, et non toute action en responsabilité contre un établissement : lorsque l'ordre a été voulu, d'autres délais s'appliquent et doivent être vérifiés au cas par cas." },
  { q: "Faut-il porter plainte pour être remboursé ?", a: "Le dépôt de plainte n'est pas une condition du remboursement, et l'action pénale restitue rarement les fonds à elle seule. Elle établit la matérialité, ouvre la voie des saisies et documente le recours civil. Les deux voies se conduisent en parallèle." },
  { q: "Peut-on agir contre la banque qui a reçu les fonds ?", a: "Cela se plaide, mais ne se présume pas. La responsabilité de la banque du bénéficiaire suppose une faute civile propre dans l'ouverture ou le fonctionnement du compte de réception, un préjudice et un lien de causalité. Les éléments issus du dispositif de vigilance anti-blanchiment contribuent à la démonstration sans ouvrir par eux-mêmes un droit à réparation pour la victime." },
  { q: "Comment identifier le titulaire du compte destinataire ?", a: "Une mesure d'instruction peut être sollicitée sur le fondement de l'article 145 du code de procédure civile, avant tout procès au fond, aux fins de communication de l'identité du titulaire du compte de réception. Son obtention n'est pas automatique : le motif légitime, la nécessité, la proportionnalité et le secret bancaire sont discutés, et c'est souvent cette étape qui conditionne la suite du dossier." },
  { q: "Quelle différence entre escroquerie et cybercriminalité ?", a: "L'escroquerie de l'article 313-1 du code pénal suppose une tromperie ayant déterminé une remise volontaire. Les atteintes aux systèmes de traitement automatisé de données, articles 323-1 à 323-4, visent l'accès, le maintien ou l'altération non consentis d'un système. Dans le premier cas la victime agit, dans le second elle subit. Une même affaire peut cumuler les deux qualifications." },
  { q: "Quelles peines l'escroquerie fait-elle encourir ?", a: "Cinq ans d'emprisonnement et 375 000 euros d'amende. Sept ans et 750 000 euros notamment lorsque les faits sont commis par une personne dépositaire de l'autorité publique ou chargée d'une mission de service public. Des peines complémentaires et la responsabilité pénale des personnes morales peuvent s'y ajouter." },
  { q: "Qu'appelle-t-on une escroquerie bancaire, et que peut-on en obtenir ?", a: "L'expression désigne les escroqueries dont le dénouement passe par un compte : carte captée, virement obtenu par manœuvre, bénéficiaire enregistré à l'insu du titulaire, ordre exécuté vers un compte de passage. Ce qui s'en obtient dépend du consentement donné à l'opération : remboursement à titre principal sur le fondement de l'article L. 133-18 du code monétaire et financier lorsqu'elle n'était pas autorisée, action fondée sur le devoir de vigilance lorsqu'elle l'était. Dans les deux cas, la banque du bénéficiaire reste assignable sur un fondement distinct." },
  { q: "Le cabinet intervient-il hors de Paris ?", a: "Oui. Le cabinet est établi 18 rue de Tilsitt, Paris 17e, et intervient devant les juridictions de l'ensemble du territoire. Le premier échange se tient par téléphone ou en visioconférence, sur pièces transmises." },
];
